apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      initContainers:
        - name: fix-permissions
          image: busybox
          command: ["sh", "-c", "chown -R 1001:1001 /app/uploads/restaurants"]
          volumeMounts:
            - name: restaurant-images
              mountPath: /app/uploads/restaurants
      containers:
        - name: backend
          image: <BACKEND_IMAGE>
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3001
          envFrom:
            - configMapRef:
                name: cash-or-card-config
            - secretRef:
                name: cash-or-card-secrets
          volumeMounts:
            - name: restaurant-images
              mountPath: /app/uploads/restaurants
          readinessProbe:
            httpGet:
              path: /health
              port: 3001
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 3001
            initialDelaySeconds: 20
            periodSeconds: 10
      volumes:
        - name: restaurant-images
          persistentVolumeClaim:
            claimName: restaurant-images-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
  ports:
    - port: 3001
      targetPort: 3001
      nodePort: 30001 # Expose on a static port for external access
  type: NodePort
