apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: restaurant-images-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: do-block-storage  # DigitalOcean block storage
